openapi: 3.1.0
info:
  title: API Documentation
  version: 1.0.0
paths:
  /api/docs/school/{schoolId}:
    get:
      deprecated: false
      tags:
      - DOCS-CONTROLLER
      parameters:
      - name: schoolId
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocsResponse'
      x-ouroboros-id: 31d97e9f-6391-4816-a40f-be9c6bf60773
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
  /api/docs:
    get:
      deprecated: false
      tags:
      - DOCS-CONTROLLER
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocsResponse'
      x-ouroboros-id: 9f86f8dd-366a-4421-84c8-26ea441eb350
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
    post:
      deprecated: false
      tags:
      - DOCS-CONTROLLER
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                data:
                  type: string
                  x-ouroboros-mock: ''
                file:
                  type: string
                  format: binary
                  x-ouroboros-mock: ''
              required:
              - data
              - file
              x-ouroboros-orders:
              - data
              - file
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DocsResponse'
      x-ouroboros-id: fc7af3ce-2318-4316-8306-6d9ada58a91d
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
  /api/docs/{id}:
    get:
      deprecated: false
      tags:
      - DOCS-CONTROLLER
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/DocsResponse'
      x-ouroboros-id: 80874c6a-5cb9-40c1-9037-2d1719bd18ee
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
    delete:
      deprecated: false
      tags:
      - DOCS-CONTROLLER
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
      x-ouroboros-id: c6c61d2b-49ac-45e5-b0a0-7048d3be3225
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
  /api/docs/{id}/download:
    get:
      deprecated: false
      tags:
      - DOCS-CONTROLLER
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
                format: byte
      x-ouroboros-id: 68c9d4a7-c0e5-4dd8-bfc9-1d5a9a9d0bbd
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
  /api/schools:
    get:
      deprecated: false
      tags:
      - SCHOOL-CONTROLLER
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SchoolResponse'
      x-ouroboros-id: a0a59a02-fa35-4dfb-8647-72719255ebd6
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
    post:
      deprecated: false
      tags:
      - SCHOOL-CONTROLLER
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchoolRequest'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SchoolResponse'
      x-ouroboros-id: 360d04b5-a7cb-40a8-b572-f32ff298a82a
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
  /api/schools/{id}:
    get:
      deprecated: false
      tags:
      - SCHOOL-CONTROLLER
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/SchoolResponse'
      x-ouroboros-id: e5419f1c-5663-4ef9-8142-d0175f11172a
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
    delete:
      deprecated: false
      tags:
      - SCHOOL-CONTROLLER
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: OK
      x-ouroboros-id: 8bc23ac6-bf02-45cf-9a3e-b8478a5e8b8e
      x-ouroboros-progress: mock
      x-ouroboros-tag: none
      x-ouroboros-diff: none
components:
  schemas:
    SchoolRequest:
      type: object
      properties:
        name:
          type: string
          x-ouroboros-mock: ''
      x-ouroboros-orders:
      - name
    SchoolResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-ouroboros-mock: ''
        name:
          type: string
          x-ouroboros-mock: ''
      x-ouroboros-orders:
      - id
      - name
    DocsResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          x-ouroboros-mock: ''
        name:
          type: string
          x-ouroboros-mock: ''
        schoolId:
          type: integer
          format: int64
          x-ouroboros-mock: ''
        schoolName:
          type: string
          x-ouroboros-mock: ''
        variables:
          type: array
          items:
            $ref: '#/components/schemas/TemplateVariable'
          x-ouroboros-mock: ''
        fileSize:
          type: integer
          format: int64
          x-ouroboros-mock: ''
        createdAt:
          type: string
          format: date-time
          x-ouroboros-mock: ''
      x-ouroboros-orders:
      - id
      - name
      - schoolId
      - schoolName
      - variables
      - fileSize
      - createdAt
    TemplateVariable:
      type: object
      properties:
        key:
          type: string
          x-ouroboros-mock: ''
        required:
          type: boolean
          x-ouroboros-mock: ''
      x-ouroboros-orders:
      - key
      - required
servers:
- url: http://localhost:8080
  description: Local Development Server
security: [
  ]
