import React, { useState, useEffect } from 'react';
import DocxViewer from './DocxViewer';

const Preview = ({ data, onDownload }) => {
    // If we have an actual file blob (e.g. from backend or upload), we can show it.
    // Since the current flow is "Fill Form -> Download", the preview might need to be generated by the backend.
    // For now, if the user uploaded a 'proof' file that happens to be docx, we could show that,
    // OR we show a placeholder saying "Click Download to Generate".
    // However, to satisfy "check broken tables", the user likely wants to see the RESULT.
    // I will add a "Generate Preview" button that mocks the flow or allows uploading a test docx.

    const [previewFile, setPreviewFile] = useState(null);

    // If the form data contains a file that is a docx (e.g. as a template or unexpected usage), use it.
    useEffect(() => {
        if (data.file && data.file.name.endsWith('.docx')) {
            setPreviewFile(data.file);
        }
    }, [data.file]);

    const handleFileUpload = (e) => {
        if (e.target.files && e.target.files[0]) {
            setPreviewFile(e.target.files[0]);
        }
    };

    const validStudents = data.students.filter(s => s.name && s.studentId);
    const studentCount = validStudents.length;

    return (
        <div className="bg-white rounded-2xl shadow-sm border border-slate-200 p-8 h-full flex flex-col">
            <div className="flex items-center justify-between mb-6">
                <h3 className="text-lg font-semibold text-slate-800">문서 미리보기</h3>
                <div className="flex items-center gap-2">
                    <label className="cursor-pointer px-3 py-1.5 bg-slate-100 hover:bg-slate-200 text-slate-600 text-xs font-bold rounded-lg transition-colors border border-slate-300">
                        DOCX 파일 열기
                        <input type="file" accept=".docx" className="hidden" onChange={handleFileUpload} />
                    </label>
                    <span className="px-3 py-1 bg-indigo-100 text-indigo-700 text-xs font-bold rounded-full">
                        {studentCount}명 대상
                    </span>
                </div>
            </div>

            <div className="bg-slate-50 border border-slate-200 rounded-xl flex-1 overflow-hidden min-h-[600px] relative">
                {previewFile ? (
                    <div className="h-full overflow-y-auto p-4 custom-scrollbar">
                        <DocxViewer file={previewFile} />
                    </div>
                ) : (
                    <div className="flex flex-col items-center justify-center h-full text-center p-8">
                        <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center mb-4">
                            <svg className="w-8 h-8 text-slate-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path></svg>
                        </div>
                        <h3 className="text-lg font-semibold text-slate-700">미리보기 준비됨</h3>
                        <p className="text-slate-500 text-sm mt-2 max-w-sm">
                            현재 브라우저에서 DOCX 렌더링을 지원합니다.<br />
                            'DOCX 파일 열기'를 클릭하여 템플릿이나 생성된 문서를 확인하세요.
                        </p>
                        <p className="text-xs text-slate-400 mt-4">
                            참고: 실제 문서 생성은 '다운로드' 버튼을 이용하세요.
                        </p>
                    </div>
                )}
            </div>

            <div className="flex justify-end mt-6">
                <button
                    onClick={onDownload}
                    className="px-8 bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-3 rounded-xl shadow-md shadow-indigo-200 transition-all flex items-center gap-2"
                >
                    <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                    다운로드 (DOCX)
                </button>
            </div>
        </div>
    );
};

export default Preview;
