{
 "title": "Spring Boot Observability",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(application)" } },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Requests Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"$app_name\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"$app_name\"})",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{application=\"$app_name\", outcome=\"SERVER_ERROR\"})"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"2.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", status=~\"5.*\", uri!=\"/actuator/prometheus\"}) / sum by(uri) (http_server_requests_seconds_count{application=\"$app_name\", uri!=\"/actuator/prometheus\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (uri, le) (\r\n    rate(http_server_requests_seconds_bucket{application=\"absent\", uri!=\"/actuator/prometheus\"}[1m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PR 95 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.95,sum(rate(http_server_requests_seconds_bucket{application=\"$app_name\", uri!=\"/actuator/prometheus\"}[1m])) by(uri, le))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=\"$app_name\"}[1m]))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "에러 로그",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{compose_service=\"app-absent-app\"}\r\n|~ \" (ERROR) \"\r\n| regexp \".*?:\\\\s(?P<msg>.*)\"\r\n| line_format \"🔴 {{.msg}}\""
    },
    {
     "direction": "backward",
     "expr": "{compose_service=\"app-absent-app\"}\r\n|~ \" (WARN) \"\r\n| regexp \".*?:\\\\s(?P<msg>.*)\"\r\n| line_format \"🟡 {{.msg}}\""
    }
   ]
  }
 ]
}