spring:
  application:
    name: absent
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      platform: postgresql
      continue-on-error: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics

  metrics:
    tags:
      application: absent

    distribution:
      percentiles-histogram:
        http.server.requests: true

      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99

      slo:
        http.server.requests: 100ms, 300ms, 500ms, 1s, 2s

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

ouroboros:
  enable: true
  server:
    url: http://localhost:8080
    description: Local Development Server

springwolf:
  enabled: false
